# Generated by Django 4.2.1 on 2023-06-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_email_email_alter_phonenumber_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name': 'Working hour', 'verbose_name_plural': 'Working hours'},
        ),
    ]
