# Generated by Django 4.2.1 on 2023-06-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_aboutpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
