# Generated by Django 4.2.1 on 2023-06-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contactspage_faqpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqpage',
            options={'verbose_name_plural': 'FAQ pages'},
        ),
    ]
