# Generated by Django 4.2.1 on 2023-06-03 19:28

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_faqpage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
