# Generated by Django 4.2.1 on 2023-09-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_page_delete_aboutpage_delete_contactspage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
