# Generated by Django 4.2.1 on 2023-09-11 11:13

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0008_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('image', models.ImageField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
