# Generated by Django 4.2.1 on 2023-09-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
