# Generated by Django 4.2.1 on 2023-11-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_promocode_isavailable_alter_promocode_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='description',
        ),
    ]
