# Generated by Django 4.2.1 on 2023-11-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_promocode_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
