# Generated by Django 4.2.1 on 2023-09-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientprofile_alter_order_patient_delete_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='patronymic',
        ),
    ]
