# Generated by Django 4.2.1 on 2023-09-14 07:03

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_patientprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(validators=[patients.models.validate_age]),
        ),
    ]
