# Generated by Django 4.2.1 on 2023-06-03 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
