# Generated by Django 4.2.1 on 2023-09-05 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_remove_doctorschedule_is_day_off'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 6)),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'date')},
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='day_of_week',
        ),
    ]
