# Generated by Django 4.2.1 on 2023-09-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctorprofile_email_doctorprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Формат: +375-XX-XXX-XX-XX', max_length=17, null=True),
        ),
    ]
