# Generated by Django 4.2.1 on 2023-09-13 21:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_alter_doctorprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 15)),
        ),
    ]
