# Generated by Django 4.2.1 on 2023-10-15 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_doctorschedule_created_at_doctorschedule_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 16)),
        ),
    ]
