# Generated by Django 4.2.1 on 2023-09-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_doctorschedule_unique_together_and_more'),
        ('orders', '0002_order_end_time_order_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_time',
        ),
        migrations.AddField(
            model_name='order',
            name='doctor_schedule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorschedule'),
            preserve_default=False,
        ),
    ]
