# Generated by Django 4.2.1 on 2023-09-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_appointment_date_remove_order_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='doctor_schedule',
        ),
    ]
