# Generated by Django 4.2.1 on 2023-09-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_doctorschedule_unique_together_and_more'),
        ('orders', '0004_remove_order_doctor_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='doctor_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorschedule'),
            preserve_default=False,
        ),
    ]
