# Generated by Django 4.2.1 on 2023-09-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает выполнения'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='pending', max_length=50),
        ),
    ]
